import type { RefObject } from 'react';
import { GitCommit, RefreshCw, Sparkles, Upload } from 'lucide-react';
import { cn } from '@/lib/cn';
import { ModelChooserPopover } from '@/components/ai/ModelChooserPopover';
import type { AiProvider } from '@/types';
import type { CommitPanelStore } from '@/components/git/useCommitPanelStore';

interface CommitComposerProps {
  panel: CommitPanelStore;
  patch: CommitPanelStore['patch'];
  messageRef: RefObject<HTMLTextAreaElement>;
  generateButtonRef: RefObject<HTMLButtonElement>;
  stagedCount: number;
  ahead: number;
  behind: number;
  canCommit: boolean;
  onCommit: () => void;
  onPush: () => void;
  onGenerate: () => void;
  onGenerateWithProvider: (provider: AiProvider) => void;
  onMessageKeyDown: (event: React.KeyboardEvent<HTMLTextAreaElement>) => void;
}

export function CommitComposer({
  panel,
  patch,
  messageRef,
  generateButtonRef,
  stagedCount,
  ahead,
  behind,
  canCommit,
  onCommit,
  onPush,
  onGenerate,
  onGenerateWithProvider,
  onMessageKeyDown,
}: CommitComposerProps) {
  return (
    <div className="border-border space-y-2 border-b px-3 py-3">
      <label className="text-fg/50 flex items-center justify-between text-[10px] font-semibold tracking-wider uppercase">
        <span>Commit message</span>
        <span className="text-fg/30 tracking-normal normal-case">⌘ ↵ to commit</span>
      </label>
      <div className="relative">
        <textarea
          ref={messageRef}
          value={panel.message}
          onChange={(event) => patch({ message: event.target.value })}
          onKeyDown={onMessageKeyDown}
          rows={3}
          placeholder={
            panel.amend ? 'Amend previous commit message…' : 'Summary (first line) + optional body'
          }
          className="border-border bg-surface text-fg placeholder:text-fg/30 focus:border-accent/60 focus:ring-accent/20 w-full resize-y rounded border px-2 py-1.5 pr-16 font-mono text-[12px] leading-snug outline-none focus:ring-2"
        />
        <button
          ref={generateButtonRef}
          type="button"
          onClick={onGenerate}
          disabled={panel.generating}
          className={cn(
            'absolute top-1.5 right-1.5 flex h-6 items-center gap-1 rounded px-1.5 text-[10px] font-semibold transition',
            panel.generating
              ? 'text-accent bg-accent/15'
              : 'text-accent/70 hover:text-accent hover:bg-accent/15',
            'disabled:cursor-wait',
          )}
          title={
            panel.generating
              ? 'Generating…'
              : stagedCount === 0
                ? 'Stage changes, then generate a commit message with AI'
                : panel.message.trim()
                  ? 'Regenerate using the current text as a hint'
                  : 'Generate commit message with AI'
          }
          aria-label="Generate commit message with AI"
        >
          {panel.generating ? (
            <RefreshCw size={11} className="animate-spin" />
          ) : (
            <Sparkles size={11} />
          )}
          <span className="tracking-wide uppercase">{panel.generating ? 'Generating' : 'AI'}</span>
        </button>
        {panel.pickerOpen && panel.providers && panel.providers.length > 1 && (
          <ModelChooserPopover
            anchorRef={generateButtonRef}
            providers={panel.providers}
            onSelect={onGenerateWithProvider}
            onDismiss={() => patch({ pickerOpen: false })}
          />
        )}
      </div>
      {panel.generationMeta && !panel.generating && (
        <div className="text-fg/40 flex items-center gap-1 text-[10px]">
          <Sparkles size={9} className="text-accent/70" />
          <span>
            Generated by {panel.generationMeta.provider}
            {panel.generationMeta.model ? ` · ${panel.generationMeta.model}` : ''}
          </span>
        </div>
      )}
      <div className="flex items-center gap-2">
        <label className="text-fg/70 hover:text-fg flex cursor-pointer items-center gap-1.5 text-[11px]">
          <input
            type="checkbox"
            checked={panel.amend}
            onChange={(event) => patch({ amend: event.target.checked })}
            className="accent-accent"
          />
          Amend last commit
        </label>
        <div className="ml-auto flex items-center gap-1.5">
          <button
            onClick={onCommit}
            disabled={!canCommit}
            className="bg-accent text-accent-fg hover:bg-accent-hover flex items-center gap-1 rounded px-2.5 py-1 text-[11px] font-semibold transition disabled:cursor-not-allowed disabled:opacity-40"
            title="Commit (⌘↵)"
          >
            {panel.committing ? (
              <RefreshCw size={11} className="animate-spin" />
            ) : (
              <GitCommit size={11} />
            )}
            Commit
          </button>
          <button
            onClick={onPush}
            disabled={panel.pushing || panel.loading}
            className="border-border bg-surface text-fg/80 hover:bg-fg/10 hover:text-fg flex items-center gap-1 rounded border px-2 py-1 text-[11px] font-medium transition disabled:cursor-not-allowed disabled:opacity-40"
            title={
              behind > 0
                ? `Behind ${behind} — pull first`
                : ahead > 0
                  ? `Push ${ahead} commit${ahead === 1 ? '' : 's'}`
                  : 'Push'
            }
          >
            {panel.pushing ? (
              <RefreshCw size={11} className="animate-spin" />
            ) : (
              <Upload size={11} />
            )}
            Push
            {ahead > 0 && <span className="text-accent-fg/80 tabular-nums">↑{ahead}</span>}
            {behind > 0 && <span className="text-rose-400 tabular-nums">↓{behind}</span>}
          </button>
        </div>
      </div>
      {panel.error && (
        <div className="rounded border border-rose-400/30 bg-rose-400/10 px-2 py-1 text-[11px] text-rose-400">
          {panel.error}
        </div>
      )}
    </div>
  );
}
