import * as i18n from '@runhq/cockpit-ui/i18n';
import type { ReactNode, RefObject } from 'react';
import { GitCommit, RefreshCw, Sparkles, Upload } from 'lucide-react';
import { cn } from '@/lib/cn';
import { ModelChooserPopover } from '@/components/ai/ModelChooserPopover';
import type { AiChatProvider } from '@/components/ai/chat-panel/aiChatProviders';
import type { CommitPanelStore } from '@/components/git/useCommitPanelStore';

interface CommitComposerProps {
  panel: CommitPanelStore;
  patch: CommitPanelStore['patch'];
  messageRef: RefObject<HTMLTextAreaElement>;
  generateButtonRef: RefObject<HTMLButtonElement>;
  stagedCount: number;
  ahead: number;
  behind: number;
  canCommit: boolean;
  onCommit: () => void;
  onPush: () => void;
  onGenerate: () => void;
  generationControls: ReactNode;
  onGenerateWithProvider: (provider: AiChatProvider) => void;
  onMessageKeyDown: (event: React.KeyboardEvent<HTMLTextAreaElement>) => void;
}

export function CommitComposer({
  panel,
  patch,
  messageRef,
  generateButtonRef,
  stagedCount,
  ahead,
  behind,
  canCommit,
  onCommit,
  onPush,
  onGenerate,
  generationControls,
  onGenerateWithProvider,
  onMessageKeyDown,
}: CommitComposerProps) {
  i18n.useLocale();
  return (
    <div className="border-border space-y-2 border-b px-3 py-3">
      <label className="text-fg/50 flex items-center justify-between text-[10px] font-semibold tracking-wider uppercase">
        <span>{i18n.t('Commit message')}</span>
        <span className="text-fg/30 tracking-normal normal-case">{i18n.t('⌘ ↵ to commit')}</span>
      </label>
      <div className="relative">
        <textarea
          ref={messageRef}
          value={panel.message}
          onChange={(event) => patch({ message: event.target.value })}
          onKeyDown={onMessageKeyDown}
          rows={3}
          placeholder={
            panel.amend
              ? i18n.t('Amend previous commit message…')
              : i18n.t('Summary (first line) + optional body')
          }
          className="border-border bg-surface text-fg placeholder:text-fg/30 focus:border-accent/60 focus:ring-accent/20 w-full resize-y rounded border px-2 py-1.5 pr-16 font-mono text-[12px] leading-snug outline-none focus:ring-2"
        />
        <button
          ref={generateButtonRef}
          type="button"
          onClick={onGenerate}
          disabled={panel.generating}
          className={cn(
            'absolute top-1.5 right-1.5 flex h-6 items-center gap-1 rounded px-1.5 text-[10px] font-semibold transition',
            panel.generating
              ? 'text-accent bg-accent/15'
              : 'text-accent/70 hover:text-accent hover:bg-accent/15',
            'disabled:cursor-wait',
          )}
          title={
            panel.generating
              ? i18n.t('Generating…')
              : stagedCount === 0
                ? i18n.t('Stage changes, then generate a commit message with AI')
                : panel.message.trim()
                  ? i18n.t('Regenerate using the current text as a hint')
                  : i18n.t('Generate commit message with AI')
          }
          aria-label={i18n.t('Generate commit message with AI')}
        >
          {panel.generating ? (
            <RefreshCw size={11} className="animate-spin" />
          ) : (
            <Sparkles size={11} />
          )}
          <span className="tracking-wide uppercase">
            {panel.generating ? i18n.t('Generating') : i18n.t('AI')}
          </span>
        </button>
        {panel.pickerOpen && panel.providers && panel.providers.length > 1 && (
          <ModelChooserPopover
            anchorRef={generateButtonRef}
            providers={panel.providers}
            onSelect={onGenerateWithProvider}
            onDismiss={() => patch({ pickerOpen: false })}
          />
        )}
      </div>
      {generationControls}
      {panel.generationMeta && !panel.generating && (
        <div className="text-fg/40 flex items-center gap-1 text-[10px]">
          <Sparkles size={9} className="text-accent/70" />
          <span>
            {i18n.rich('Generated by {value1}{value2}', {
              value1: panel.generationMeta.provider,
              value2: panel.generationMeta.model ? ` · ${panel.generationMeta.model}` : '',
            })}
          </span>
        </div>
      )}
      <div className="flex items-center gap-2">
        <label className="text-fg/70 hover:text-fg flex cursor-pointer items-center gap-1.5 text-[11px]">
          {i18n.rich('{value1}Amend last commit', {
            value1: (
              <input
                type="checkbox"
                checked={panel.amend}
                onChange={(event) => patch({ amend: event.target.checked })}
                className="accent-accent"
              />
            ),
          })}
        </label>
        <div className="ml-auto flex items-center gap-1.5">
          <button
            onClick={onCommit}
            disabled={!canCommit}
            className="bg-accent text-accent-fg hover:bg-accent-hover flex items-center gap-1 rounded px-2.5 py-1 text-[11px] font-semibold transition disabled:cursor-not-allowed disabled:opacity-40"
            title={i18n.t('Commit (⌘↵)')}
          >
            {i18n.rich('{value1}Commit', {
              value1: panel.committing ? (
                <RefreshCw size={11} className="animate-spin" />
              ) : (
                <GitCommit size={11} />
              ),
            })}
          </button>
          <button
            onClick={onPush}
            disabled={panel.pushing || panel.loading}
            className="border-border bg-surface text-fg/80 hover:bg-fg/10 hover:text-fg flex items-center gap-1 rounded border px-2 py-1 text-[11px] font-medium transition disabled:cursor-not-allowed disabled:opacity-40"
            title={
              behind > 0
                ? i18n.t('Behind {behind} — pull first', { behind: behind })
                : ahead > 0
                  ? i18n.t('Push {ahead} commit{plural2}', {
                      ahead: ahead,
                      plural2: ahead === 1 ? '' : 's',
                    })
                  : i18n.t('Push')
            }
          >
            {i18n.rich('{value1}Push{value2}{value3}', {
              value1: panel.pushing ? (
                <RefreshCw size={11} className="animate-spin" />
              ) : (
                <Upload size={11} />
              ),
              value2: ahead > 0 && <span className="text-accent-fg/80 tabular-nums">↑{ahead}</span>,
              value3: behind > 0 && <span className="text-rose-400 tabular-nums">↓{behind}</span>,
            })}
          </button>
        </div>
      </div>
      {panel.error && (
        <div className="rounded border border-rose-400/30 bg-rose-400/10 px-2 py-1 text-[11px] text-rose-400">
          {panel.error}
        </div>
      )}
    </div>
  );
}
