import { useEffect, useRef, useState } from 'react';
import {
  AlertCircle,
  Check,
  Copy,
  Loader2,
  RefreshCw,
  Scissors,
  Sparkles,
  Square,
  X,
} from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { cn } from '@/lib/cn';
import type { AiStreamUsage, UseAiStreamApi } from '@/lib/useAiStream';
import { ReasoningPill } from './ReasoningPill';
import { COMPACT_MARKDOWN_COMPONENTS, ROOMY_MARKDOWN_COMPONENTS } from './markdownComponents';

interface AiAnswerProps {
  /** State + actions from `useAiStream`. The component is otherwise
   * stateless — every UI surface owns its own stream and decides
   * which prompt to issue inside `onRegenerate`. */
  stream: Pick<
    UseAiStreamApi,
    | 'status'
    | 'text'
    | 'reasoning'
    | 'reasoningStartedAtMs'
    | 'reasoningEndedAtMs'
    | 'error'
    | 'usage'
    | 'durationMs'
    | 'finishReason'
  >;
  /** Optional. Re-issue the same request. The button only appears
   * when this is provided AND the stream is not currently busy. */
  onRegenerate?: () => void;
  /** Optional. Cancel an in-flight stream. Stops the UI from
   * appending tokens; the backend stream may still finish silently. */
  onCancel?: () => void;
  /** Optional. Hide the component entirely. The popovers/drawers
   * use this to render nothing when the user hasn't triggered the
   * AI yet (instead of showing an empty card). */
  onClose?: () => void;
  /** Visual density. `compact` is for inline answers next to a
   * trigger button; `roomy` is for full-width drawers and dialogs. */
  density?: 'compact' | 'roomy';
  /** Optional badge above the answer (e.g. "Diff Explainer",
   * "Log Triage"). Useful when several streams render side-by-side. */
  label?: string;
  /** Provider/model attribution suffix. The component appends a
   * pico-summary "Generated by … in 1.4s" once the stream is done.
   * Pass `false` to suppress (e.g. inside the chat panel where the
   * surrounding UI already shows the model). */
  showAttribution?: boolean;
  className?: string;
}

/// Streaming-aware answer card.
///
/// Renders one of four states based on `stream.status`:
///   - `streaming`: live markdown (rendered as plain text first to
///     keep cost low, then re-rendered as proper markdown after the
///     final chunk) + a pulsing caret
///   - `done`: full markdown + copy/regenerate buttons + attribution
///   - `error`: red alert card + regenerate
///   - `idle` / `cancelled`: nothing (the parent decides what to show)
export function AiAnswer({
  stream,
  onRegenerate,
  onCancel,
  onClose,
  density = 'roomy',
  label,
  showAttribution = true,
  className,
}: AiAnswerProps) {
  const [copied, setCopied] = useState(false);
  const scrollRef = useRef<HTMLDivElement | null>(null);

  // Auto-scroll the answer body to keep new tokens visible.
  // Only nudge during streaming — once done, leave the scroll position
  // wherever the user landed it.
  useEffect(() => {
    if (stream.status === 'streaming' && scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [stream.text, stream.status]);

  if (stream.status === 'idle' || stream.status === 'cancelled') {
    return null;
  }

  const isStreaming = stream.status === 'streaming';
  const isError = stream.status === 'error';

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(stream.text);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      // Clipboard API can be unavailable in some Tauri webview
      // builds with restricted permissions. Fail silently — the
      // user can select-and-copy as a fallback.
    }
  };

  return (
    <div
      className={cn(
        'border-border/60 bg-surface-raised/60 rounded-app-sm flex flex-col border',
        density === 'compact' ? 'gap-1.5 p-2.5' : 'gap-2 p-3',
        isError && 'border-status-error/40 bg-status-error/5',
        className,
      )}
    >
      <div
        className={cn(
          'flex items-center justify-between',
          density === 'compact' ? 'text-[10.5px]' : 'text-[11px]',
        )}
      >
        <div className="text-fg-dim flex items-center gap-1.5 font-semibold tracking-[0.12em] uppercase">
          {isError ? (
            <AlertCircle className="text-status-error h-3 w-3" />
          ) : isStreaming ? (
            <Loader2 className="text-accent h-3 w-3 animate-spin" />
          ) : (
            <Sparkles className="text-accent h-3 w-3" />
          )}
          <span>{label ?? (isError ? 'AI error' : 'AI')}</span>
        </div>
        <div className="flex items-center gap-1">
          {!isStreaming && !isError && stream.text.trim() && (
            <button
              type="button"
              onClick={handleCopy}
              className="text-fg-dim hover:bg-fg/10 hover:text-fg flex h-6 items-center gap-1 rounded px-1.5 text-[10.5px] transition"
              title="Copy"
            >
              {copied ? (
                <>
                  <Check className="h-3 w-3" /> Copied
                </>
              ) : (
                <>
                  <Copy className="h-3 w-3" /> Copy
                </>
              )}
            </button>
          )}
          {isStreaming && onCancel && (
            <button
              type="button"
              onClick={onCancel}
              className="text-fg-dim hover:bg-fg/10 hover:text-fg flex h-6 items-center gap-1 rounded px-1.5 text-[10.5px] transition"
              title="Stop"
            >
              <Square className="h-3 w-3" />
              Stop
            </button>
          )}
          {!isStreaming && onRegenerate && (
            <button
              type="button"
              onClick={onRegenerate}
              className="text-fg-dim hover:bg-fg/10 hover:text-fg flex h-6 items-center gap-1 rounded px-1.5 text-[10.5px] transition"
              title="Regenerate"
            >
              <RefreshCw className="h-3 w-3" /> Regenerate
            </button>
          )}
          {onClose && (
            <button
              type="button"
              onClick={onClose}
              className="text-fg-dim hover:bg-fg/10 hover:text-fg flex h-6 w-6 items-center justify-center rounded transition"
              title="Dismiss"
            >
              <X className="h-3 w-3" />
            </button>
          )}
        </div>
      </div>

      {!isError && (
        <ReasoningPill
          reasoning={stream.reasoning}
          startedAtMs={stream.reasoningStartedAtMs}
          endedAtMs={stream.reasoningEndedAtMs}
        />
      )}

      {isError ? (
        <p className="text-status-error text-[11.5px] leading-snug wrap-break-word">
          {stream.error ?? 'Something went wrong while talking to the AI provider.'}
        </p>
      ) : (
        <div
          ref={scrollRef}
          className={cn(
            'ai-answer-body text-fg/90 overflow-y-auto text-[12px] leading-[1.55] wrap-break-word',
            density === 'compact' ? 'max-h-[260px]' : 'max-h-[440px]',
          )}
        >
          {/* During streaming we render via ReactMarkdown too — it
              handles partial markdown gracefully (an unclosed bold
              just renders as plain `**text`). The pulsing caret marks
              the live edge. The component map is shared with the
              chat panel (`markdownComponents.tsx`) so headings,
              tables, blockquotes, etc. render identically across
              every AI surface — see that file's docstring for the
              full rationale. */}
          <ReactMarkdown
            remarkPlugins={[remarkGfm]}
            components={
              density === 'compact' ? COMPACT_MARKDOWN_COMPONENTS : ROOMY_MARKDOWN_COMPONENTS
            }
          >
            {stream.text}
          </ReactMarkdown>
          {isStreaming && (
            <span className="bg-accent ml-0.5 inline-block h-3 w-1.5 animate-pulse align-middle" />
          )}
        </div>
      )}

      {/* Truncation notice. Read-only surfaces (diff explainer, log
       *  triage, project explain) don't get a Continue button — these
       *  flows are one-shot answers, not chats — but the user still
       *  needs to know the answer is incomplete. The hint nudges
       *  them toward the right fix (per-provider `max_output_tokens`)
       *  and toward Regenerate when one is offered. */}
      {!isError && stream.status === 'done' && stream.finishReason === 'length' && (
        <div
          className={cn(
            'border-status-starting/30 bg-status-starting/5 flex items-center gap-2',
            'rounded-md border px-2.5 py-1.5 text-[11px]',
          )}
          role="status"
        >
          <Scissors className="text-status-starting h-3 w-3 shrink-0" />
          <span className="text-fg-dim flex-1 leading-snug">
            Response was cut off (max tokens reached). Increase{' '}
            <span className="text-fg/70 font-mono">max_output_tokens</span> in AI Settings
            {onRegenerate ? ' or click Regenerate.' : '.'}
          </span>
        </div>
      )}

      {showAttribution && stream.status === 'done' && (
        <AttributionLine usage={stream.usage} durationMs={stream.durationMs} />
      )}
    </div>
  );
}

function AttributionLine({
  usage,
  durationMs,
}: {
  usage: AiStreamUsage | null;
  durationMs: number | null;
}) {
  const parts: string[] = [];
  if (durationMs !== null) {
    parts.push(durationMs >= 1000 ? `${(durationMs / 1000).toFixed(1)}s` : `${durationMs} ms`);
  }
  if (usage?.completionTokens != null && usage.completionTokens > 0) {
    parts.push(`${usage.completionTokens} out`);
  }
  if (usage?.promptTokens != null && usage.promptTokens > 0) {
    parts.push(`${usage.promptTokens} in`);
  }
  if (parts.length === 0) return null;
  return (
    <div className="text-fg-dim/80 flex items-center gap-1 text-[10px]">
      <Sparkles className="text-accent/60 h-2.5 w-2.5" />
      <span>{parts.join(' · ')}</span>
    </div>
  );
}
