use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMessage {
    pub role: String,
    pub content: String,
}

impl ChatMessage {
    pub fn system(content: impl Into<String>) -> Self {
        Self {
            role: "system".into(),
            content: content.into(),
        }
    }
    pub fn user(content: impl Into<String>) -> Self {
        Self {
            role: "user".into(),
            content: content.into(),
        }
    }
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ChatOptions {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_tokens: Option<u32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatResponse {
    pub content: String,
    /// Model the server actually used. Some gateways (OpenRouter, etc.)
    /// remap requested models — we surface the actual one for the
    /// "Generated by …" footer.
    #[serde(default)]
    pub model: Option<String>,
    /// Token usage when the provider reports it. Optional because many
    /// OpenAI-compatible servers (Ollama, LM Studio) omit `usage`.
    #[serde(default)]
    pub prompt_tokens: Option<u32>,
    #[serde(default)]
    pub completion_tokens: Option<u32>,
}

/// Result of a "Test connection" probe — short, structured, never
/// blocking the UI. We keep `latency_ms` separate from `model_echo`
/// because some local providers ship empty content even on a healthy
/// 200, which would otherwise make the green-check feel flaky.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TestResult {
    pub ok: bool,
    pub latency_ms: u64,
    #[serde(default)]
    pub model: Option<String>,
    #[serde(default)]
    pub message: Option<String>,
}

/// One chunk of a streaming AI response.
///
/// The variant tags are flat (no nesting) on purpose: the desktop
/// shell forwards these straight over a Tauri `Channel<StreamChunk>`
/// to the React side, and a flat tagged union maps cleanly to a
/// TypeScript discriminated union without any custom serde tomfoolery.
#[derive(Debug, Clone, Serialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum StreamChunk {
    /// A token (or token group) of the model's actual answer.
    /// Frontends should append `text` to whatever they're currently
    /// rendering as the response body.
    Delta { text: String },
    /// A token (or token group) of the model's chain-of-thought /
    /// reasoning trace. We split this from `Delta` because reasoning
    /// models (DeepSeek-R1, GLM-4.x, Qwen-QwQ, OpenAI o-series) emit
    /// pages of internal monologue that the user typically wants
    /// hidden behind a collapsible toggle. Sources we recognise:
    ///   - `delta.reasoning_content` (DeepSeek, GLM, Together)
    ///   - `delta.reasoning` (OpenRouter normalised, OpenAI o-series)
    ///   - `<think>...</think>` blocks inside `delta.content` (Qwen
    ///     QwQ, R1 distills shipping over plain `content`)
    Reasoning { text: String },
    /// Move all previously-emitted [`StreamChunk::Delta`] tokens
    /// into the reasoning bucket. Fired when the splitter sees a
    /// closing `</think>` tag without ever seeing a matching
    /// opener — a pattern used by reasoning models served behind
    /// proxies that strip the opener but pass the closer through
    /// (OpenRouter normalisation is the most common case). The
    /// frontend reducer concats `text` onto `reasoning` and resets
    /// `text` to the empty string.
    ReclassifyAsReasoning,
    /// The stream completed cleanly. Carries the fully-accumulated
    /// content (so callers don't have to re-stitch it themselves)
    /// and the usage block when the provider reported it.
    Done {
        content: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        reasoning: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        model: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        prompt_tokens: Option<u32>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        completion_tokens: Option<u32>,
        /// Why the model stopped generating, as reported by the
        /// provider (`finish_reason` on OpenAI-compatible APIs).
        ///
        /// The values we explicitly act on:
        ///   - `"stop"` — the model decided it was done.
        ///   - `"length"` — generation hit `max_tokens` (or the
        ///     model's context cap). The answer is **truncated**;
        ///     the UI must surface this so the user doesn't think
        ///     the assistant gave up mid-sentence. A "Continue"
        ///     affordance is the standard remedy.
        ///   - `"content_filter"` — provider safety filter tripped.
        ///   - `null` — provider didn't report (some local servers).
        ///
        /// We keep this as a free-form `Option<String>` rather than
        /// an enum so adding a new finish reason on the frontend
        /// doesn't require a backend release. The whole point is
        /// to never silently swallow a truncation event again.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        finish_reason: Option<String>,
    },
    /// A provider-side error (4xx/5xx, malformed SSE, network blip).
    /// We funnel transport failures through the same channel so the
    /// UI has a single subscribe-and-render path.
    Error { message: String },
}
