import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
await build({
  entryPoints: [fileURLToPath(new URL('./src/main.mjs', import.meta.url))],
  outfile: fileURLToPath(
    new URL('../../apps/desktop/src-tauri/resources/agent-runtime/bridge.mjs', import.meta.url),
  ),
  bundle: true,
  platform: 'node',
  target: 'node22',
  format: 'esm',
  banner: {
    js: '/* RunHQ agent runtime — generated by pnpm agent:build */\nimport { createRequire as runhqCreateRequire } from "node:module"; const require = runhqCreateRequire(import.meta.url);',
  },
});
